<?php

namespace Kirki\Ecommerce\Database\Seeders;

use Kirki\Ecommerce\App\Models\Category;
use Kirki\Ecommerce\Framework\Database\Seeder;
use Kirki\Ecommerce\Framework\Supports\Facades\Log;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'id' => 1,
                'name' => 'Men',
                'slug' => 'men',
                'description' => 'Apparel and footwear for men.',
                'parent_id' => null,
                'level' => 1,
                'ordering' => 1,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Men\'s Tops',
                'slug' => 'mens-tops',
                'description' => 'T-shirts, shirts, and sweaters for men.',
                'parent_id' => 1,
                'level' => 2,
                'ordering' => 1,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Men\'s Bottoms',
                'slug' => 'mens-bottoms',
                'description' => 'Jeans, chinos, and trousers for men.',
                'parent_id' => 1,
                'level' => 2,
                'ordering' => 2,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 4,
                'name' => 'Men\'s Outerwear',
                'slug' => 'mens-outerwear',
                'description' => 'Jackets and coats for men.',
                'parent_id' => 1,
                'level' => 2,
                'ordering' => 3,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Men\'s Footwear',
                'slug' => 'mens-footwear',
                'description' => 'Sneakers and shoes for men.',
                'parent_id' => 1,
                'level' => 2,
                'ordering' => 4,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Women',
                'slug' => 'women',
                'description' => 'Apparel and footwear for women.',
                'parent_id' => null,
                'level' => 1,
                'ordering' => 2,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Women\'s Tops',
                'slug' => 'womens-tops',
                'description' => 'T-shirts, blouses, and sweaters for women.',
                'parent_id' => 6,
                'level' => 2,
                'ordering' => 1,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 8,
                'name' => 'Women\'s Dresses',
                'slug' => 'womens-dresses',
                'description' => 'Dresses for every occasion.',
                'parent_id' => 6,
                'level' => 2,
                'ordering' => 2,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 9,
                'name' => 'Women\'s Bottoms',
                'slug' => 'womens-bottoms',
                'description' => 'Jeans and leggings for women.',
                'parent_id' => 6,
                'level' => 2,
                'ordering' => 3,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 10,
                'name' => 'Women\'s Outerwear',
                'slug' => 'womens-outerwear',
                'description' => 'Jackets and coats for women.',
                'parent_id' => 6,
                'level' => 2,
                'ordering' => 4,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 11,
                'name' => 'Women\'s Footwear',
                'slug' => 'womens-footwear',
                'description' => 'Sneakers and shoes for women.',
                'parent_id' => 6,
                'level' => 2,
                'ordering' => 5,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 12,
                'name' => 'Kids',
                'slug' => 'kids',
                'description' => 'Apparel for boys and girls.',
                'parent_id' => null,
                'level' => 1,
                'ordering' => 3,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 13,
                'name' => 'Boys Clothing',
                'slug' => 'boys-clothing',
                'description' => 'Everyday apparel for boys.',
                'parent_id' => 12,
                'level' => 2,
                'ordering' => 1,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 14,
                'name' => 'Girls Clothing',
                'slug' => 'girls-clothing',
                'description' => 'Everyday apparel for girls.',
                'parent_id' => 12,
                'level' => 2,
                'ordering' => 2,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 15,
                'name' => 'Accessories',
                'slug' => 'accessories',
                'description' => 'Bags, eyewear, and jewelry to complete any outfit.',
                'parent_id' => null,
                'level' => 1,
                'ordering' => 4,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 16,
                'name' => 'Bags',
                'slug' => 'bags',
                'description' => 'Totes, crossbody bags, and backpacks.',
                'parent_id' => 15,
                'level' => 2,
                'ordering' => 1,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 17,
                'name' => 'Belts & Wallets',
                'slug' => 'belts-wallets',
                'description' => 'Leather belts and wallets.',
                'parent_id' => 15,
                'level' => 2,
                'ordering' => 2,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 18,
                'name' => 'Eyewear',
                'slug' => 'eyewear',
                'description' => 'Sunglasses and prescription frames.',
                'parent_id' => 15,
                'level' => 2,
                'ordering' => 3,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 19,
                'name' => 'Watches & Jewelry',
                'slug' => 'watches-jewelry',
                'description' => 'Watches, smartwatches, and jewelry.',
                'parent_id' => 15,
                'level' => 2,
                'ordering' => 4,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
            [
                'id' => 20,
                'name' => 'Hats & Caps',
                'slug' => 'hats-caps',
                'description' => 'Caps, beanies, and hats.',
                'parent_id' => 15,
                'level' => 2,
                'ordering' => 5,
                'is_active' => true,
                'is_deletable' => true,
                'created_by' => 1,
            ],
        ];

        Category::query()->insert($categories);

        Log::info('CategorySeeder run successfully');
    }
}
