<?php

namespace Kirki\Ecommerce\Database\Seeders;

class SeedCatalog
{
    /**
     * Curated fashion brands matching the product catalog.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_brands()
    {
        return [
            ['id' => 1, 'name' => 'Nike', 'slug' => 'nike', 'description' => 'Athletic footwear, apparel, and performance gear.'],
            ['id' => 2, 'name' => 'Adidas', 'slug' => 'adidas', 'description' => 'Sportswear, sneakers, and activewear essentials.'],
            ['id' => 3, 'name' => 'Levi\'s', 'slug' => 'levis', 'description' => 'Iconic denim and casual apparel since 1853.'],
            ['id' => 4, 'name' => 'Zara', 'slug' => 'zara', 'description' => 'Contemporary fashion for men and women.'],
            ['id' => 5, 'name' => 'H&M', 'slug' => 'hm', 'description' => 'Affordable, on-trend fashion and basics.'],
            ['id' => 6, 'name' => 'Patagonia', 'slug' => 'patagonia', 'description' => 'Outdoor clothing and sustainably made gear.'],
            ['id' => 7, 'name' => 'Uniqlo', 'slug' => 'uniqlo', 'description' => 'Simple, high-quality everyday essentials.'],
            ['id' => 8, 'name' => 'Gap', 'slug' => 'gap', 'description' => 'Classic American casual wear for the whole family.'],
            ['id' => 9, 'name' => 'Ralph Lauren', 'slug' => 'ralph-lauren', 'description' => 'Timeless, polished American style.'],
            ['id' => 10, 'name' => 'Under Armour', 'slug' => 'under-armour', 'description' => 'Performance activewear and training gear.'],
            ['id' => 11, 'name' => 'Puma', 'slug' => 'puma', 'description' => 'Sport-inspired footwear and streetwear.'],
            ['id' => 12, 'name' => 'Calvin Klein', 'slug' => 'calvin-klein', 'description' => 'Modern, minimalist fashion essentials.'],
            ['id' => 13, 'name' => 'Tommy Hilfiger', 'slug' => 'tommy-hilfiger', 'description' => 'Classic American cool with a preppy edge.'],
            ['id' => 14, 'name' => 'Vans', 'slug' => 'vans', 'description' => 'Skate-inspired sneakers and streetwear.'],
            ['id' => 15, 'name' => 'Ray-Ban', 'slug' => 'ray-ban', 'description' => 'Iconic sunglasses and eyewear.'],
            ['id' => 16, 'name' => 'Fossil', 'slug' => 'fossil', 'description' => 'Watches, smartwatches, and leather goods.'],
            ['id' => 17, 'name' => 'Marc Jacobs', 'slug' => 'marc-jacobs', 'description' => 'Bold, fashion-forward bags and accessories.'],
            ['id' => 18, 'name' => 'Coach', 'slug' => 'coach', 'description' => 'Premium leather bags and accessories.'],
        ];
    }

    /**
     * Curated merchandising and descriptive tags.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_tags()
    {
        return [
            ['id' => 1, 'name' => 'Bestseller', 'slug' => 'bestseller', 'description' => 'Top-selling products in the store.'],
            ['id' => 2, 'name' => 'New Arrival', 'slug' => 'new-arrival', 'description' => 'Recently added products.'],
            ['id' => 3, 'name' => 'Sale', 'slug' => 'sale', 'description' => 'Products currently on sale.'],
            ['id' => 4, 'name' => 'Free Shipping', 'slug' => 'free-shipping', 'description' => 'Eligible for free shipping.'],
            ['id' => 5, 'name' => 'Premium', 'slug' => 'premium', 'description' => 'High-end and premium products.'],
            ['id' => 6, 'name' => 'Limited Edition', 'slug' => 'limited-edition', 'description' => 'Limited availability items.'],
            ['id' => 7, 'name' => 'Men\'s', 'slug' => 'mens', 'description' => 'Apparel and accessories for men.'],
            ['id' => 8, 'name' => 'Women\'s', 'slug' => 'womens', 'description' => 'Apparel and accessories for women.'],
            ['id' => 9, 'name' => 'Kids', 'slug' => 'kids', 'description' => 'Apparel for children.'],
            ['id' => 10, 'name' => 'Footwear', 'slug' => 'footwear', 'description' => 'Shoes, sneakers, and boots.'],
            ['id' => 11, 'name' => 'Outerwear', 'slug' => 'outerwear', 'description' => 'Jackets, coats, and layers.'],
            ['id' => 12, 'name' => 'Denim', 'slug' => 'denim', 'description' => 'Jeans and denim apparel.'],
            ['id' => 13, 'name' => 'Activewear', 'slug' => 'activewear', 'description' => 'Performance and training apparel.'],
            ['id' => 14, 'name' => 'Accessories', 'slug' => 'accessories', 'description' => 'Bags, eyewear, and jewelry.'],
            ['id' => 15, 'name' => 'Eco-Friendly', 'slug' => 'eco-friendly', 'description' => 'Sustainably made products.'],
            ['id' => 16, 'name' => 'Formal', 'slug' => 'formal', 'description' => 'Dressy and occasion wear.'],
            ['id' => 17, 'name' => 'Casual', 'slug' => 'casual', 'description' => 'Everyday, relaxed wear.'],
            ['id' => 18, 'name' => 'Dresses', 'slug' => 'dresses', 'description' => 'Dresses for every occasion.'],
        ];
    }

    /**
     * Customer segment tags for customer records.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_customer_tags()
    {
        return ['vip', 'repeat-buyer', 'newsletter', 'wholesale', 'first-order'];
    }

    /**
     * Product catalog with deterministic relationships.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_products()
    {
        return [
            [
                'title' => 'Nike Dri-FIT Men\'s T-Shirt',
                'brand_id' => 1,
                'categories' => [1, 2],
                'tags' => [1, 2, 7, 17],
                'price' => 2900,
                'sale_price' => 2400,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'tops',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'T-Shirt',
                'flagship' => false,
            ],
            [
                'title' => 'Adidas Essentials Track Jacket',
                'brand_id' => 2,
                'categories' => [1, 4],
                'tags' => [7, 11, 17],
                'price' => 6500,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'outerwear',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Track Jacket',
                'flagship' => false,
            ],
            [
                'title' => 'Levi\'s 501 Original Jeans',
                'brand_id' => 3,
                'categories' => [1, 3],
                'tags' => [1, 7, 12],
                'price' => 9800,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Classic',
                'category_type' => 'bottoms',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Jeans',
                'flagship' => false,
            ],
            [
                'title' => 'Uniqlo Oxford Button-Down Shirt',
                'brand_id' => 7,
                'categories' => [1, 2],
                'tags' => [7, 16],
                'price' => 3900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'tops',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Shirt',
                'flagship' => false,
            ],
            [
                'title' => 'Gap Slim Fit Chinos',
                'brand_id' => 8,
                'categories' => [1, 3],
                'tags' => [3, 7],
                'price' => 5900,
                'sale_price' => 4900,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'bottoms',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Chinos',
                'flagship' => false,
            ],
            [
                'title' => 'Patagonia Better Sweater Fleece Jacket',
                'brand_id' => 6,
                'categories' => [1, 4],
                'tags' => [5, 7, 11],
                'price' => 14900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'outerwear',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Fleece Jacket',
                'flagship' => false,
            ],
            [
                'title' => 'Ralph Lauren Classic Polo Shirt',
                'brand_id' => 9,
                'categories' => [1, 2],
                'tags' => [5, 7, 16],
                'price' => 8900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'tops',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Polo Shirt',
                'flagship' => false,
            ],
            [
                'title' => 'Under Armour Tech Training Tee',
                'brand_id' => 10,
                'categories' => [1, 2],
                'tags' => [7, 13],
                'price' => 3200,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'tops',
                'gender' => 'men',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Training Tee',
                'flagship' => false,
            ],
            [
                'title' => 'Nike Air Max 90',
                'brand_id' => 1,
                'categories' => [1, 5],
                'tags' => [1, 7, 10],
                'price' => 13000,
                'sale_price' => 11000,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'footwear',
                'gender' => 'men',
                'variant_scheme' => 'footwear-size',
                'image_label' => 'Sneaker',
                'flagship' => true,
            ],
            [
                'title' => 'Vans Old Skool Sneakers',
                'brand_id' => 14,
                'categories' => [1, 5],
                'tags' => [2, 7, 10],
                'price' => 7000,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'footwear',
                'gender' => 'men',
                'variant_scheme' => 'footwear-size',
                'image_label' => 'Sneaker',
                'flagship' => false,
            ],
            [
                'title' => 'Adidas Ultraboost Light',
                'brand_id' => 2,
                'categories' => [1, 5],
                'tags' => [7, 10],
                'price' => 19000,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'footwear',
                'gender' => 'men',
                'variant_scheme' => 'footwear-size',
                'image_label' => 'Running Shoe',
                'flagship' => false,
            ],
            [
                'title' => 'Zara Oversized Blazer',
                'brand_id' => 4,
                'categories' => [6, 10],
                'tags' => [2, 8, 11],
                'price' => 8900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'outerwear',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Blazer',
                'flagship' => false,
            ],
            [
                'title' => 'H&M Cotton Crew Neck T-Shirt',
                'brand_id' => 5,
                'categories' => [6, 7],
                'tags' => [3, 8, 17],
                'price' => 1200,
                'sale_price' => 900,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'tops',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'T-Shirt',
                'flagship' => false,
            ],
            [
                'title' => 'Zara Floral Wrap Dress',
                'brand_id' => 4,
                'categories' => [6, 8],
                'tags' => [2, 8, 18],
                'price' => 6900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'dresses',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Wrap Dress',
                'flagship' => false,
            ],
            [
                'title' => 'Calvin Klein Slim Fit Midi Dress',
                'brand_id' => 12,
                'categories' => [6, 8],
                'tags' => [5, 8, 18],
                'price' => 12900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'dresses',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Midi Dress',
                'flagship' => true,
            ],
            [
                'title' => 'Levi\'s 501 Original Jeans (Women\'s)',
                'brand_id' => 3,
                'categories' => [6, 9],
                'tags' => [1, 8, 12],
                'price' => 9800,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Classic',
                'category_type' => 'bottoms',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Jeans',
                'flagship' => false,
            ],
            [
                'title' => 'Uniqlo Ultra Light Down Jacket',
                'brand_id' => 7,
                'categories' => [6, 10],
                'tags' => [3, 8, 11],
                'price' => 7900,
                'sale_price' => 6900,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'outerwear',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Down Jacket',
                'flagship' => false,
            ],
            [
                'title' => 'Tommy Hilfiger Essential Knit Sweater',
                'brand_id' => 13,
                'categories' => [6, 7],
                'tags' => [8, 16],
                'price' => 8500,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'tops',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Knit Sweater',
                'flagship' => false,
            ],
            [
                'title' => 'Under Armour Women\'s Training Leggings',
                'brand_id' => 10,
                'categories' => [6, 9],
                'tags' => [8, 13],
                'price' => 4900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'bottoms',
                'gender' => 'women',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Leggings',
                'flagship' => false,
            ],
            [
                'title' => 'Adidas Ultraboost Light (Women\'s)',
                'brand_id' => 2,
                'categories' => [6, 11],
                'tags' => [8, 10],
                'price' => 18000,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'footwear',
                'gender' => 'women',
                'variant_scheme' => 'footwear-size',
                'image_label' => 'Running Shoe',
                'flagship' => false,
            ],
            [
                'title' => 'Nike Air Max 90 (Women\'s)',
                'brand_id' => 1,
                'categories' => [6, 11],
                'tags' => [1, 8, 10],
                'price' => 13000,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'footwear',
                'gender' => 'women',
                'variant_scheme' => 'footwear-size',
                'image_label' => 'Sneaker',
                'flagship' => true,
            ],
            [
                'title' => 'Puma Suede Classic Sneakers',
                'brand_id' => 11,
                'categories' => [6, 11],
                'tags' => [8, 10],
                'price' => 7500,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'footwear',
                'gender' => 'women',
                'variant_scheme' => 'footwear-size',
                'image_label' => 'Sneaker',
                'flagship' => false,
            ],
            [
                'title' => 'Adidas Kids Graphic Tee',
                'brand_id' => 2,
                'categories' => [12, 13],
                'tags' => [9, 17],
                'price' => 1900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'kids',
                'gender' => 'kids',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Graphic Tee',
                'flagship' => false,
            ],
            [
                'title' => 'H&M Girls Printed Dress',
                'brand_id' => 5,
                'categories' => [12, 14],
                'tags' => [3, 9, 18],
                'price' => 2200,
                'sale_price' => 1800,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'kids',
                'gender' => 'kids',
                'variant_scheme' => 'apparel-size',
                'image_label' => 'Printed Dress',
                'flagship' => false,
            ],
            [
                'title' => 'Coach Leather Tote Bag',
                'brand_id' => 18,
                'categories' => [15, 16],
                'tags' => [5, 14],
                'price' => 24900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'accessory-color',
                'image_label' => 'Tote Bag',
                'flagship' => false,
            ],
            [
                'title' => 'Marc Jacobs Mini Crossbody Bag',
                'brand_id' => 17,
                'categories' => [15, 16],
                'tags' => [2, 14],
                'price' => 19900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'accessory-color',
                'image_label' => 'Crossbody Bag',
                'flagship' => false,
            ],
            [
                'title' => 'Fossil Leather Wallet',
                'brand_id' => 16,
                'categories' => [15, 17],
                'tags' => [14],
                'price' => 5900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'accessory-color',
                'image_label' => 'Wallet',
                'flagship' => false,
            ],
            [
                'title' => 'Ray-Ban Aviator Classic Sunglasses',
                'brand_id' => 15,
                'categories' => [15, 18],
                'tags' => [5, 14],
                'price' => 16900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'none',
                'image_label' => 'Sunglasses',
                'accent_color' => '#6B3F52',
                'flagship' => false,
            ],
            [
                'title' => 'Fossil Gen 6 Smartwatch',
                'brand_id' => 16,
                'categories' => [15, 19],
                'tags' => [2, 14],
                'price' => 29900,
                'sale_price' => null,
                'status' => 'draft',
                'ribbon' => null,
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'none',
                'image_label' => 'Smartwatch',
                'accent_color' => '#2F6F6B',
                'flagship' => false,
            ],
            [
                'title' => 'Levi\'s Canvas Baseball Cap',
                'brand_id' => 3,
                'categories' => [15, 20],
                'tags' => [14, 17],
                'price' => 2500,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'none',
                'image_label' => 'Baseball Cap',
                'accent_color' => '#B5603D',
                'flagship' => false,
            ],
            [
                'title' => 'Patagonia Wool Beanie',
                'brand_id' => 6,
                'categories' => [15, 20],
                'tags' => [5, 14],
                'price' => 2900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'none',
                'image_label' => 'Beanie',
                'accent_color' => '#4F6B4F',
                'flagship' => false,
            ],
            [
                'title' => 'H&M Silk Scarf',
                'brand_id' => 5,
                'categories' => [15],
                'tags' => [3, 14],
                'price' => 1900,
                'sale_price' => 1500,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'accessories',
                'gender' => 'unisex',
                'variant_scheme' => 'none',
                'image_label' => 'Silk Scarf',
                'accent_color' => '#E3A9A0',
                'flagship' => false,
            ],
        ];
    }

    /**
     * Curated coupon definitions for seed data.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_coupons()
    {
        return [
            [
                'method' => 'code',
                'title' => 'Winter Outerwear Sale 20% Off',
                'code' => 'WINTER20',
                'discount_type' => 'amount-off',
                'discount_target' => 'order',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 20,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'all-products',
                'spend_condition_type' => 'min-cart-amount',
                'spend_condition_value' => 5000,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-12-31 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 1000,
                'has_customer_limit' => true,
                'customer_limit' => 1,
                'current_usage_count' => 12,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Denim Collection 15% Off',
                'code' => 'DENIM15',
                'discount_type' => 'amount-off',
                'discount_target' => 'products',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 15,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'specific-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-06-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-06-30 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 500,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 5,
                'is_active' => true,
                'product_ids' => [3, 16],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Sneaker Bundle $50 Off',
                'code' => 'KICKS50',
                'discount_type' => 'amount-off',
                'discount_target' => 'products',
                'discount_value_type' => 'fixed',
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => 5000,
                'eligible_item_type' => 'specific-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-03-01 00:00:00',
                'has_end_datetime' => false,
                'end_datetime' => null,
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => false,
                'usage_limit' => null,
                'has_customer_limit' => true,
                'customer_limit' => 2,
                'current_usage_count' => 0,
                'is_active' => true,
                'product_ids' => [9, 10, 11, 20, 21, 22],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Free Shipping on Outerwear',
                'code' => 'WARMSHIP',
                'discount_type' => 'free-shipping',
                'discount_target' => null,
                'discount_value_type' => null,
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => 'min-cart-amount',
                'spend_condition_value' => 3000,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-15 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-01-15 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 2000,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 48,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [4, 10],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'automatic',
                'title' => 'Buy 2 Get 1 Free Accessories',
                'code' => null,
                'discount_type' => 'buy-x-get-y',
                'discount_target' => 'products',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => 'min-items',
                'spend_condition_value' => 2,
                'reward_quantity' => 1,
                'reward_value' => 100,
                'start_datetime' => '2025-04-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-04-01 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => false,
                'usage_limit' => null,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 3,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [15],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'VIP Customer Exclusive',
                'code' => 'VIP25',
                'discount_type' => 'amount-off',
                'discount_target' => 'order',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 25,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'all-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-01 00:00:00',
                'has_end_datetime' => false,
                'end_datetime' => null,
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'specific-customers',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 100,
                'has_customer_limit' => true,
                'customer_limit' => 3,
                'current_usage_count' => 2,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [],
                'customer_ids' => [1, 2, 3],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Kids Clearance $10 Off',
                'code' => 'KIDS10',
                'discount_type' => 'amount-off',
                'discount_target' => 'products',
                'discount_value_type' => 'fixed',
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => 1000,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => 'min-cart-amount',
                'spend_condition_value' => 2000,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-05-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-05-01 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 300,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 7,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [12],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'First Order Welcome',
                'code' => 'WELCOME10',
                'discount_type' => 'amount-off',
                'discount_target' => 'order',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 10,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'all-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-01 00:00:00',
                'has_end_datetime' => false,
                'end_datetime' => null,
                'target_countries' => null,
                'first_time_buyer_only' => true,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => false,
                'usage_limit' => null,
                'has_customer_limit' => true,
                'customer_limit' => 1,
                'current_usage_count' => 15,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
        ];
    }

    /**
     * Curated customer records for seed data.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_customers()
    {
        return [
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@example.com',
                'phone' => '+1-555-0101',
                'tags' => 'vip,repeat-buyer',
                'note' => 'Prefers express shipping. Regular denim and sneaker buyer.',
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Chen',
                'email' => 'michael.chen@example.com',
                'phone' => '+1-555-0102',
                'tags' => 'newsletter,repeat-buyer',
                'note' => 'Interested in outerwear deals and seasonal drops.',
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Rodriguez',
                'email' => 'emily.rodriguez@example.com',
                'phone' => '+1-555-0103',
                'tags' => 'vip,newsletter',
                'note' => 'Dress and accessories enthusiast.',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Wilson',
                'email' => 'james.wilson@example.com',
                'phone' => '+1-555-0104',
                'tags' => 'wholesale',
                'note' => 'Bulk orders for corporate uniform apparel.',
            ],
            [
                'first_name' => 'Aisha',
                'last_name' => 'Patel',
                'email' => 'aisha.patel@example.com',
                'phone' => '+1-555-0105',
                'tags' => 'first-order,newsletter',
                'note' => 'New customer signed up via homepage popup.',
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Kim',
                'email' => 'david.kim@example.com',
                'phone' => '+1-555-0106',
                'tags' => 'repeat-buyer',
                'note' => 'Frequently purchases sneakers and activewear.',
            ],
            [
                'first_name' => 'Olivia',
                'last_name' => 'Brown',
                'email' => 'olivia.brown@example.com',
                'phone' => '+1-555-0107',
                'tags' => 'vip,wholesale',
                'note' => 'Corporate account for team apparel orders.',
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Martinez',
                'email' => 'daniel.martinez@example.com',
                'phone' => '+1-555-0108',
                'tags' => 'newsletter',
                'note' => 'Subscribed to sale alerts.',
            ],
            [
                'first_name' => 'Sophia',
                'last_name' => 'Taylor',
                'email' => 'sophia.taylor@example.com',
                'phone' => '+1-555-0109',
                'tags' => 'repeat-buyer,first-order',
                'note' => 'Recently switched from guest checkout to registered account.',
            ],
            [
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'email' => 'ahmed.hassan@example.com',
                'phone' => '+880-1710-000010',
                'tags' => 'vip,repeat-buyer,newsletter',
                'note' => 'Local customer in Bangladesh. Primary test account.',
            ],
        ];
    }

    /**
     * Resolve brand name by identifier.
     *
     * @param int $brand_id Brand identifier.
     *
     * @return string
     * @since 1.0.0
     */
    public static function get_brand_name($brand_id)
    {
        foreach (static::get_brands() as $brand) {
            if ($brand['id'] === $brand_id) {
                return $brand['name'];
            }
        }

        return 'Unknown';
    }

    /**
     * Resolve category label by type key.
     *
     * @param string $category_type Category type key.
     *
     * @return string
     * @since 1.0.0
     */
    public static function get_category_label($category_type)
    {
        $labels = [
            'tops' => 'tops',
            'bottoms' => 'bottoms',
            'outerwear' => 'outerwear',
            'dresses' => 'dresses',
            'footwear' => 'footwear',
            'kids' => 'kids apparel',
            'accessories' => 'accessories',
        ];

        return $labels[$category_type] ?? 'products';
    }
}
