<?php

namespace Kirki\Ecommerce\Database\Seeders;

class SeedCatalog
{
    /**
     * Curated brands matching the product catalog.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_brands()
    {
        return [
            ['id' => 1, 'name' => 'Apple', 'slug' => 'apple', 'description' => 'Premium consumer electronics and software.'],
            ['id' => 2, 'name' => 'Samsung', 'slug' => 'samsung', 'description' => 'Global leader in smartphones and home appliances.'],
            ['id' => 3, 'name' => 'Google', 'slug' => 'google', 'description' => 'Pixel phones and smart home technology.'],
            ['id' => 4, 'name' => 'OnePlus', 'slug' => 'oneplus', 'description' => 'Flagship smartphones at competitive prices.'],
            ['id' => 5, 'name' => 'Dell', 'slug' => 'dell', 'description' => 'Business and consumer laptops and monitors.'],
            ['id' => 6, 'name' => 'Lenovo', 'slug' => 'lenovo', 'description' => 'ThinkPad and IdeaPad laptops for professionals.'],
            ['id' => 7, 'name' => 'ASUS', 'slug' => 'asus', 'description' => 'Gaming laptops and PC components.'],
            ['id' => 8, 'name' => 'Sony', 'slug' => 'sony', 'description' => 'Audio, imaging, and entertainment products.'],
            ['id' => 9, 'name' => 'Bose', 'slug' => 'bose', 'description' => 'Premium audio equipment and headphones.'],
            ['id' => 10, 'name' => 'JBL', 'slug' => 'jbl', 'description' => 'Portable speakers and audio accessories.'],
            ['id' => 11, 'name' => 'Canon', 'slug' => 'canon', 'description' => 'Cameras, lenses, and imaging solutions.'],
            ['id' => 12, 'name' => 'GoPro', 'slug' => 'gopro', 'description' => 'Action cameras for adventure and sports.'],
            ['id' => 13, 'name' => 'Nike', 'slug' => 'nike', 'description' => 'Athletic footwear, apparel, and equipment.'],
            ['id' => 14, 'name' => 'Adidas', 'slug' => 'adidas', 'description' => 'Sportswear and performance running shoes.'],
            ['id' => 15, 'name' => 'Levi\'s', 'slug' => 'levis', 'description' => 'Iconic denim and casual apparel.'],
            ['id' => 16, 'name' => 'Patagonia', 'slug' => 'patagonia', 'description' => 'Outdoor clothing and sustainable gear.'],
            ['id' => 17, 'name' => 'Zara', 'slug' => 'zara', 'description' => 'Contemporary fashion for men and women.'],
            ['id' => 18, 'name' => 'H&M', 'slug' => 'hm', 'description' => 'Affordable fashion and basics.'],
            ['id' => 19, 'name' => 'Dyson', 'slug' => 'dyson', 'description' => 'Vacuum cleaners and home technology.'],
            ['id' => 20, 'name' => 'KitchenAid', 'slug' => 'kitchenaid', 'description' => 'Stand mixers and kitchen appliances.'],
            ['id' => 21, 'name' => 'Instant Pot', 'slug' => 'instant-pot', 'description' => 'Multi-use pressure cookers and kitchen gadgets.'],
            ['id' => 22, 'name' => 'Ninja', 'slug' => 'ninja', 'description' => 'Air fryers, blenders, and kitchen appliances.'],
            ['id' => 23, 'name' => 'IKEA', 'slug' => 'ikea', 'description' => 'Affordable furniture and home accessories.'],
            ['id' => 24, 'name' => 'West Elm', 'slug' => 'west-elm', 'description' => 'Modern furniture and home decor.'],
            ['id' => 25, 'name' => 'Casper', 'slug' => 'casper', 'description' => 'Mattresses and sleep products.'],
            ['id' => 26, 'name' => 'Philips', 'slug' => 'philips', 'description' => 'Smart lighting and personal care devices.'],
            ['id' => 27, 'name' => 'Olay', 'slug' => 'olay', 'description' => 'Skincare and anti-aging products.'],
            ['id' => 28, 'name' => 'CeraVe', 'slug' => 'cerave', 'description' => 'Dermatologist-developed skincare.'],
            ['id' => 29, 'name' => 'The Ordinary', 'slug' => 'the-ordinary', 'description' => 'Clinical formulations with transparent pricing.'],
            ['id' => 30, 'name' => 'Oral-B', 'slug' => 'oral-b', 'description' => 'Electric toothbrushes and oral care.'],
        ];
    }

    /**
     * Curated merchandising and descriptive tags.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_tags()
    {
        return [
            ['id' => 1, 'name' => 'Bestseller', 'slug' => 'bestseller', 'description' => 'Top-selling products in the store.'],
            ['id' => 2, 'name' => 'New Arrival', 'slug' => 'new-arrival', 'description' => 'Recently added products.'],
            ['id' => 3, 'name' => 'Sale', 'slug' => 'sale', 'description' => 'Products currently on sale.'],
            ['id' => 4, 'name' => 'Free Shipping', 'slug' => 'free-shipping', 'description' => 'Eligible for free shipping.'],
            ['id' => 5, 'name' => 'Premium', 'slug' => 'premium', 'description' => 'High-end and premium products.'],
            ['id' => 6, 'name' => 'Limited Edition', 'slug' => 'limited-edition', 'description' => 'Limited availability items.'],
            ['id' => 7, 'name' => 'Smartphone', 'slug' => 'smartphone', 'description' => 'Mobile phones and smartphones.'],
            ['id' => 8, 'name' => 'Laptop', 'slug' => 'laptop', 'description' => 'Laptops and notebooks.'],
            ['id' => 9, 'name' => 'Headphones', 'slug' => 'headphones', 'description' => 'Headphones and earbuds.'],
            ['id' => 10, 'name' => 'Footwear', 'slug' => 'footwear', 'description' => 'Shoes and athletic footwear.'],
            ['id' => 11, 'name' => 'Apparel', 'slug' => 'apparel', 'description' => 'Clothing and fashion items.'],
            ['id' => 12, 'name' => 'Kitchen Appliance', 'slug' => 'kitchen-appliance', 'description' => 'Kitchen tools and appliances.'],
            ['id' => 13, 'name' => 'Furniture', 'slug' => 'furniture', 'description' => 'Furniture and home furnishings.'],
            ['id' => 14, 'name' => 'Skincare', 'slug' => 'skincare', 'description' => 'Skincare and beauty products.'],
            ['id' => 15, 'name' => 'Camera', 'slug' => 'camera', 'description' => 'Cameras and imaging equipment.'],
        ];
    }

    /**
     * Customer segment tags for customer records.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_customer_tags()
    {
        return ['vip', 'repeat-buyer', 'newsletter', 'wholesale', 'first-order'];
    }

    /**
     * Product catalog with deterministic relationships.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_products()
    {
        return [
            [
                'title' => 'Apple iPhone 15 Pro',
                'brand_id' => 1,
                'categories' => [1, 2],
                'tags' => [1, 2, 5, 7],
                'price' => 99900,
                'sale_price' => 94900,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'electronics',
                'flagship' => true,
            ],
            [
                'title' => 'Samsung Galaxy S24 Ultra',
                'brand_id' => 2,
                'categories' => [1, 2],
                'tags' => [1, 5, 7],
                'price' => 119900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Google Pixel 8 Pro',
                'brand_id' => 3,
                'categories' => [1, 2],
                'tags' => [2, 7],
                'price' => 89900,
                'sale_price' => 84900,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'OnePlus 12',
                'brand_id' => 4,
                'categories' => [1, 2],
                'tags' => [3, 7],
                'price' => 79900,
                'sale_price' => 74900,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'MacBook Air M3',
                'brand_id' => 1,
                'categories' => [1, 3],
                'tags' => [1, 5, 8],
                'price' => 129900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'electronics',
                'flagship' => true,
            ],
            [
                'title' => 'Dell XPS 15',
                'brand_id' => 5,
                'categories' => [1, 3],
                'tags' => [5, 8],
                'price' => 149900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Lenovo ThinkPad X1 Carbon',
                'brand_id' => 6,
                'categories' => [1, 3],
                'tags' => [1, 8],
                'price' => 139900,
                'sale_price' => 129900,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'ASUS ROG Zephyrus G14',
                'brand_id' => 7,
                'categories' => [1, 3],
                'tags' => [6, 8],
                'price' => 159900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Limited Edition',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Sony WH-1000XM5 Headphones',
                'brand_id' => 8,
                'categories' => [1],
                'tags' => [1, 5, 9],
                'price' => 34900,
                'sale_price' => 29900,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Apple AirPods Pro 2',
                'brand_id' => 1,
                'categories' => [1],
                'tags' => [1, 2, 9],
                'price' => 24900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Bose QuietComfort Ultra Earbuds',
                'brand_id' => 9,
                'categories' => [1],
                'tags' => [5, 9],
                'price' => 29900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'JBL Flip 6 Bluetooth Speaker',
                'brand_id' => 10,
                'categories' => [1],
                'tags' => [4, 9],
                'price' => 12900,
                'sale_price' => 10900,
                'status' => 'published',
                'ribbon' => 'Free Shipping',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Canon EOS R6 Mark II',
                'brand_id' => 11,
                'categories' => [1],
                'tags' => [5, 15],
                'price' => 249900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'GoPro HERO12 Black',
                'brand_id' => 12,
                'categories' => [1],
                'tags' => [2, 15],
                'price' => 39900,
                'sale_price' => 37900,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'electronics',
                'flagship' => false,
            ],
            [
                'title' => 'Nike Air Max 90',
                'brand_id' => 13,
                'categories' => [4, 5],
                'tags' => [1, 10, 11],
                'price' => 13000,
                'sale_price' => 11000,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'fashion',
                'flagship' => true,
            ],
            [
                'title' => 'Adidas Ultraboost Light',
                'brand_id' => 14,
                'categories' => [4, 5],
                'tags' => [10, 11],
                'price' => 19000,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'fashion',
                'flagship' => false,
            ],
            [
                'title' => 'Levi\'s 501 Original Jeans',
                'brand_id' => 15,
                'categories' => [4, 5],
                'tags' => [1, 11],
                'price' => 9800,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Classic',
                'category_type' => 'fashion',
                'flagship' => false,
            ],
            [
                'title' => 'Patagonia Better Sweater Fleece Jacket',
                'brand_id' => 16,
                'categories' => [4, 5],
                'tags' => [5, 11],
                'price' => 14900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'fashion',
                'flagship' => false,
            ],
            [
                'title' => 'Zara Oversized Blazer',
                'brand_id' => 17,
                'categories' => [4, 6],
                'tags' => [2, 11],
                'price' => 8900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'fashion',
                'flagship' => false,
            ],
            [
                'title' => 'H&M Cotton Crew Neck T-Shirt',
                'brand_id' => 18,
                'categories' => [4, 5],
                'tags' => [3, 11],
                'price' => 1200,
                'sale_price' => 900,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'fashion',
                'flagship' => false,
            ],
            [
                'title' => 'Dyson V15 Detect Vacuum',
                'brand_id' => 19,
                'categories' => [7],
                'tags' => [1, 5],
                'price' => 74900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'home',
                'flagship' => false,
            ],
            [
                'title' => 'KitchenAid Artisan Stand Mixer',
                'brand_id' => 20,
                'categories' => [7, 8],
                'tags' => [1, 12],
                'price' => 44900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'kitchen',
                'flagship' => false,
            ],
            [
                'title' => 'Instant Pot Duo Plus 9-in-1',
                'brand_id' => 21,
                'categories' => [7, 8],
                'tags' => [1, 12],
                'price' => 12900,
                'sale_price' => 10900,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'kitchen',
                'flagship' => false,
            ],
            [
                'title' => 'Ninja Foodi Air Fryer Max XL',
                'brand_id' => 22,
                'categories' => [7, 8],
                'tags' => [2, 12],
                'price' => 19900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'New Arrival',
                'category_type' => 'kitchen',
                'flagship' => false,
            ],
            [
                'title' => 'IKEA MALM Bed Frame',
                'brand_id' => 23,
                'categories' => [7, 9],
                'tags' => [4, 13],
                'price' => 24900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Free Shipping',
                'category_type' => 'furniture',
                'flagship' => false,
            ],
            [
                'title' => 'West Elm Mid-Century Desk',
                'brand_id' => 24,
                'categories' => [7, 9],
                'tags' => [5, 13],
                'price' => 59900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Premium',
                'category_type' => 'furniture',
                'flagship' => false,
            ],
            [
                'title' => 'Casper Original Mattress',
                'brand_id' => 25,
                'categories' => [7, 9],
                'tags' => [1, 13],
                'price' => 89900,
                'sale_price' => 79900,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'furniture',
                'flagship' => false,
            ],
            [
                'title' => 'Philips Hue White and Color Ambiance Starter Kit',
                'brand_id' => 26,
                'categories' => [7],
                'tags' => [2, 5],
                'price' => 19900,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Smart Home',
                'category_type' => 'home',
                'flagship' => false,
            ],
            [
                'title' => 'Olay Regenerist Micro-Sculpting Cream',
                'brand_id' => 27,
                'categories' => [10],
                'tags' => [1, 14],
                'price' => 2899,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => 'Bestseller',
                'category_type' => 'beauty',
                'flagship' => false,
            ],
            [
                'title' => 'CeraVe Moisturizing Cream',
                'brand_id' => 28,
                'categories' => [10],
                'tags' => [1, 14],
                'price' => 1899,
                'sale_price' => null,
                'status' => 'published',
                'ribbon' => null,
                'category_type' => 'beauty',
                'flagship' => false,
            ],
            [
                'title' => 'The Ordinary Niacinamide 10% + Zinc 1%',
                'brand_id' => 29,
                'categories' => [10],
                'tags' => [3, 14],
                'price' => 590,
                'sale_price' => 490,
                'status' => 'published',
                'ribbon' => 'Sale',
                'category_type' => 'beauty',
                'flagship' => false,
            ],
            [
                'title' => 'Oral-B iO Series 9 Electric Toothbrush',
                'brand_id' => 30,
                'categories' => [10],
                'tags' => [5, 14],
                'price' => 29900,
                'sale_price' => null,
                'status' => 'draft',
                'ribbon' => 'Premium',
                'category_type' => 'beauty',
                'flagship' => false,
            ],
        ];
    }

    /**
     * Curated coupon definitions for seed data.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_coupons()
    {
        return [
            [
                'method' => 'code',
                'title' => 'Winter Sale 20% Off',
                'code' => 'WINTER20',
                'discount_type' => 'amount-off',
                'discount_target' => 'order',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 20,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'all-products',
                'spend_condition_type' => 'min-cart-amount',
                'spend_condition_value' => 5000,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-12-31 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 1000,
                'has_customer_limit' => true,
                'customer_limit' => 1,
                'current_usage_count' => 12,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Electronics Flash Sale',
                'code' => 'TECH15',
                'discount_type' => 'amount-off',
                'discount_target' => 'products',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 15,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-06-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-06-30 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 500,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 5,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [1],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Smartphone Bundle Discount',
                'code' => 'PHONE500',
                'discount_type' => 'amount-off',
                'discount_target' => 'products',
                'discount_value_type' => 'fixed',
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => 5000,
                'eligible_item_type' => 'specific-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-03-01 00:00:00',
                'has_end_datetime' => false,
                'end_datetime' => null,
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => false,
                'usage_limit' => null,
                'has_customer_limit' => true,
                'customer_limit' => 2,
                'current_usage_count' => 0,
                'is_active' => true,
                'product_ids' => [1, 2, 3, 4],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Fashion Free Shipping',
                'code' => 'STYLESHIP',
                'discount_type' => 'free-shipping',
                'discount_target' => null,
                'discount_value_type' => null,
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => 'min-cart-amount',
                'spend_condition_value' => 3000,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-15 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-01-15 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 2000,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 48,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [4],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'automatic',
                'title' => 'Buy 2 Get 1 Free Beauty',
                'code' => null,
                'discount_type' => 'buy-x-get-y',
                'discount_target' => 'products',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => 'min-items',
                'spend_condition_value' => 2,
                'reward_quantity' => 1,
                'reward_value' => 100,
                'start_datetime' => '2025-04-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-04-01 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => false,
                'usage_limit' => null,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 3,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [10],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'VIP Customer Exclusive',
                'code' => 'VIP25',
                'discount_type' => 'amount-off',
                'discount_target' => 'order',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 25,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'all-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-01 00:00:00',
                'has_end_datetime' => false,
                'end_datetime' => null,
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'specific-customers',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 100,
                'has_customer_limit' => true,
                'customer_limit' => 3,
                'current_usage_count' => 2,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [],
                'customer_ids' => [1, 2, 3],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'Kitchen Essentials $10 Off',
                'code' => 'COOK10',
                'discount_type' => 'amount-off',
                'discount_target' => 'products',
                'discount_value_type' => 'fixed',
                'discount_amount_percentage' => null,
                'base_discount_amount_fixed' => 1000,
                'eligible_item_type' => 'specific-categories',
                'spend_condition_type' => 'min-cart-amount',
                'spend_condition_value' => 5000,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-05-01 00:00:00',
                'has_end_datetime' => true,
                'end_datetime' => '2026-05-01 23:59:59',
                'target_countries' => null,
                'first_time_buyer_only' => false,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => true,
                'usage_limit' => 300,
                'has_customer_limit' => false,
                'customer_limit' => null,
                'current_usage_count' => 7,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [8],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
            [
                'method' => 'code',
                'title' => 'First Order Welcome',
                'code' => 'WELCOME10',
                'discount_type' => 'amount-off',
                'discount_target' => 'order',
                'discount_value_type' => 'percentage',
                'discount_amount_percentage' => 10,
                'base_discount_amount_fixed' => null,
                'eligible_item_type' => 'all-products',
                'spend_condition_type' => null,
                'spend_condition_value' => null,
                'reward_quantity' => null,
                'reward_value' => null,
                'start_datetime' => '2025-01-01 00:00:00',
                'has_end_datetime' => false,
                'end_datetime' => null,
                'target_countries' => null,
                'first_time_buyer_only' => true,
                'customer_include_eligibility' => 'everyone',
                'customer_exclude_eligibility' => 'none',
                'has_usage_limit' => false,
                'usage_limit' => null,
                'has_customer_limit' => true,
                'customer_limit' => 1,
                'current_usage_count' => 15,
                'is_active' => true,
                'product_ids' => [],
                'category_ids' => [],
                'customer_ids' => [],
                'exclude_customer_ids' => [],
            ],
        ];
    }

    /**
     * Curated customer records for seed data.
     *
     * @return array
     * @since 1.0.0
     */
    public static function get_customers()
    {
        return [
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@example.com',
                'phone' => '+1-555-0101',
                'tags' => 'vip,repeat-buyer',
                'note' => 'Prefers express shipping. Regular electronics buyer.',
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Chen',
                'email' => 'michael.chen@example.com',
                'phone' => '+1-555-0102',
                'tags' => 'newsletter,repeat-buyer',
                'note' => 'Interested in laptop deals and accessories.',
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Rodriguez',
                'email' => 'emily.rodriguez@example.com',
                'phone' => '+1-555-0103',
                'tags' => 'vip,newsletter',
                'note' => 'Fashion and beauty enthusiast.',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Wilson',
                'email' => 'james.wilson@example.com',
                'phone' => '+1-555-0104',
                'tags' => 'wholesale',
                'note' => 'Bulk orders for kitchen appliances.',
            ],
            [
                'first_name' => 'Aisha',
                'last_name' => 'Patel',
                'email' => 'aisha.patel@example.com',
                'phone' => '+1-555-0105',
                'tags' => 'first-order,newsletter',
                'note' => 'New customer signed up via homepage popup.',
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Kim',
                'email' => 'david.kim@example.com',
                'phone' => '+1-555-0106',
                'tags' => 'repeat-buyer',
                'note' => 'Frequently purchases headphones and audio gear.',
            ],
            [
                'first_name' => 'Olivia',
                'last_name' => 'Brown',
                'email' => 'olivia.brown@example.com',
                'phone' => '+1-555-0107',
                'tags' => 'vip,wholesale',
                'note' => 'Corporate account for office furniture.',
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Martinez',
                'email' => 'daniel.martinez@example.com',
                'phone' => '+1-555-0108',
                'tags' => 'newsletter',
                'note' => 'Subscribed to sale alerts.',
            ],
            [
                'first_name' => 'Sophia',
                'last_name' => 'Taylor',
                'email' => 'sophia.taylor@example.com',
                'phone' => '+1-555-0109',
                'tags' => 'repeat-buyer,first-order',
                'note' => 'Recently switched from guest checkout to registered account.',
            ],
            [
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'email' => 'ahmed.hassan@example.com',
                'phone' => '+880-1710-000010',
                'tags' => 'vip,repeat-buyer,newsletter',
                'note' => 'Local customer in Bangladesh. Primary test account.',
            ],
        ];
    }

    /**
     * Resolve brand name by identifier.
     *
     * @param int $brand_id Brand identifier.
     *
     * @return string
     * @since 1.0.0
     */
    public static function get_brand_name($brand_id)
    {
        foreach (static::get_brands() as $brand) {
            if ($brand['id'] === $brand_id) {
                return $brand['name'];
            }
        }

        return 'Unknown';
    }

    /**
     * Resolve category label by type key.
     *
     * @param string $category_type Category type key.
     *
     * @return string
     * @since 1.0.0
     */
    public static function get_category_label($category_type)
    {
        $labels = [
            'electronics' => 'electronics',
            'fashion' => 'fashion',
            'kitchen' => 'kitchenware',
            'home' => 'home and living',
            'furniture' => 'furniture',
            'beauty' => 'beauty and health',
        ];

        return $labels[$category_type] ?? 'products';
    }
}
