<?php

/**
 * Per-country address field rules.
 *
 * For each country: whether the state and postal code fields are hidden,
 * optional or required, and the term that country uses for its subdivision.
 *
 * Imported from Google's libaddressinput (Apache-2.0) by
 * bin/import-address-rules.php. That upstream is maintained and changes over
 * time, so this file can be regenerated by re-running the importer - it is
 * not a one-time conversion. Prefer re-importing over editing by hand.
 */

return [
    'AF' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'AX' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'AL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'DZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'AS' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'AD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'AO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'AI' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'AQ' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'AG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'AR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'AM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'AW' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'AU' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'AT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'AZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BH' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BB' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'BZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BJ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BQ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'canton',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BW' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BV' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BR' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'IO' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'BN' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BF' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'BI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'KH' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'CA' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'CV' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KY' => [
        'state' => [
            'mode' => 'required',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CF' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'prefecture',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'TD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'CL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CN' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'CX' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CC' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CO' => [
        'state' => [
            'mode' => 'required',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'CG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'CK' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'CR' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'HR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CU' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CW' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'CY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'CZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'CD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'DK' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'DJ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'DM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'DO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'TL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'municipality',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'EC' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'EG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SV' => [
        'state' => [
            'mode' => 'required',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'GQ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'ER' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'EE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'county',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'ET' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'FK' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'FO' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'FJ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'FI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'FR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GF' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'PF' => [
        'state' => [
            'mode' => 'required',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'TF' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'GA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'GM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'division',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'GE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'DE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GH' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'GI' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'GR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GL' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'GP' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GU' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'GG' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GN' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'GW' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'GY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'HT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'HM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'HN' => [
        'state' => [
            'mode' => 'required',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'HK' => [
        'state' => [
            'mode' => 'required',
            'label' => 'area',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'HU' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'IS' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IN' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'ID' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IQ' => [
        'state' => [
            'mode' => 'required',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'county',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IT' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'JM' => [
        'state' => [
            'mode' => 'required',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'JP' => [
        'state' => [
            'mode' => 'required',
            'label' => 'prefecture',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'JE' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'JO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'XK' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KW' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'LA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'LV' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'municipality',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'LB' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'LS' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'LR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'county',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'LY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'LI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'LT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'LU' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MO' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'MK' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'municipality',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MW' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'MY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MV' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'ML' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'MT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'IM' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MH' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MQ' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'MU' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'YT' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MX' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'FM' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MC' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MN' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'ME' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'municipality',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MS' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'MA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'NA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'NR' => [
        'state' => [
            'mode' => 'required',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'NP' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'NL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'NC' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'NZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'NI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'NE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'NG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'NU' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'NF' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'KP' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'MP' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'NO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'OM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'PK' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'PW' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'PS' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'PA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'PG' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'PY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'PE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'PH' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'PN' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'PL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'PT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'PR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'QA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'RE' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'RO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'county',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'RU' => [
        'state' => [
            'mode' => 'required',
            'label' => 'oblast',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'RW' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SH' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'KN' => [
        'state' => [
            'mode' => 'required',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'LC' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'quarter',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'PM' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'VC' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'parish',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BL' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'MF' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'WS' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'ST' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SN' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'RS' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SC' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SL' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'council',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'SX' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SK' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'SI' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'municipality',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SB' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SO' => [
        'state' => [
            'mode' => 'required',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'ZA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'GS' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'KR' => [
        'state' => [
            'mode' => 'required',
            'label' => 'do_si',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'SS' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'ES' => [
        'state' => [
            'mode' => 'required',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'LK' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SD' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'SJ' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'SZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'SE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'county',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'CH' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'SY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'TW' => [
        'state' => [
            'mode' => 'required',
            'label' => 'county',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'TJ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'TZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'TH' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'BS' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'TG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'TK' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'TO' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'TT' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'TN' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'TR' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'TM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'TC' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'TV' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'island',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'UG' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'district',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'UA' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'oblast',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'AE' => [
        'state' => [
            'mode' => 'required',
            'label' => 'emirate',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'GB' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'US' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'UM' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'UY' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'department',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'UZ' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'VU' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'VA' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'VE' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'VN' => [
        'state' => [
            'mode' => 'required',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'VG' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'VI' => [
        'state' => [
            'mode' => 'required',
            'label' => 'state',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'WF' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'required',
        ],
    ],
    'EH' => [
        'state' => [
            'mode' => 'hidden',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'YE' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'region',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
    'ZM' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'optional',
        ],
    ],
    'ZW' => [
        'state' => [
            'mode' => 'optional',
            'label' => 'province',
        ],
        'postal_code' => [
            'mode' => 'hidden',
        ],
    ],
];
