<?php

namespace Kirki\Ecommerce\Supports\Facades;

use Kirki\Ecommerce\Facade;

/**
 * @see https://carbon.nesbot.com/docs/
 *
 * @method static bool can_be_created_from_format(?string $date, string $format)
 * @method static \Ecommerce\Supports\Carbon|null create($year = 0, $month = 1, $day = 1, $hour = 0, $minute = 0, $second = 0, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_from_date($year = null, $month = null, $day = null, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon|null create_from_format($format, $time, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon|null create_from_iso_format(string $format, string $time, $timezone = null, ?string $locale = 'en', $translator = null)
 * @method static \Ecommerce\Supports\Carbon|null create_from_locale_format(string $format, string $locale, string $time, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon|null create_from_locale_iso_format(string $format, string $locale, string $time, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_from_time($hour = 0, $minute = 0, $second = 0, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_from_time_string(string $time, \DateTimeZone|string|int|null $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_from_timestamp(string|int|float $timestamp, \DateTimeZone|string|int|null $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_from_timestamp_ms(string|int|float $timestamp, \DateTimeZone|string|int|null $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_from_timestamp_ms_utc($timestamp)
 * @method static \Ecommerce\Supports\Carbon create_from_timestamp_utc(string|int|float $timestamp)
 * @method static \Ecommerce\Supports\Carbon create_midnight_date($year = null, $month = null, $day = null, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon|null create_safe($year = null, $month = null, $day = null, $hour = null, $minute = null, $second = null, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon create_strict(?int $year = 0, ?int $month = 1, ?int $day = 1, ?int $hour = 0, ?int $minute = 0, ?int $second = 0, $timezone = null)
 * @method static void disable_human_diff_option($humanDiffOption)
 * @method static void enable_human_diff_option($humanDiffOption)
 * @method static mixed execute_with_locale(string $locale, callable $func)
 * @method static \Ecommerce\Supports\Carbon from_serialized($value)
 * @method static array get_available_locales()
 * @method static array get_available_locales_info()
 * @method static array get_days()
 * @method static ?string get_fallback_locale()
 * @method static array get_formats_to_iso_replacements()
 * @method static int get_human_diff_options()
 * @method static array get_iso_units()
 * @method static array|false get_last_errors()
 * @method static string get_locale()
 * @method static int get_mid_day_at()
 * @method static string get_time_format_by_precision(string $unit_precision)
 * @method static string|\Closure|null get_translation_message_with($translator, string $key, ?string $locale = null, ?string $default = null)
 * @method static \Ecommerce\Supports\Carbon|null get_test_now()
 * @method static mixed get_translator()
 * @method static int get_week_ends_at(?string $locale = null)
 * @method static int get_week_starts_at(?string $locale = null)
 * @method static array get_weekend_days()
 * @method static bool has_format(string $date, string $format)
 * @method static bool has_format_with_modifiers(string $date, string $format)
 * @method static bool has_macro($name)
 * @method static bool has_relative_keywords(?string $time)
 * @method static bool has_test_now()
 * @method static \Ecommerce\Supports\Carbon instance(\DateTimeInterface $date)
 * @method static bool is_immutable()
 * @method static bool is_modifiable_unit($unit)
 * @method static bool is_mutable()
 * @method static bool is_strict_mode_enabled()
 * @method static bool locale_has_diff_one_day_words(string $locale)
 * @method static bool locale_has_diff_syntax(string $locale)
 * @method static bool locale_has_diff_two_day_words(string $locale)
 * @method static bool locale_has_period_syntax($locale)
 * @method static bool locale_has_short_units(string $locale)
 * @method static void macro(string $name, ?callable $macro)
 * @method static \Ecommerce\Supports\Carbon|null make($var, \DateTimeZone|string|null $timezone = null)
 * @method static void mixin(object|string $mixin)
 * @method static \Ecommerce\Supports\Carbon now(\DateTimeZone|string|int|null $timezone = null)
 * @method static \Ecommerce\Supports\Carbon parse(\DateTimeInterface|\Carbon\WeekDay|\Carbon\Month|string|int|float|null $time, \DateTimeZone|string|int|null $timezone = null)
 * @method static \Ecommerce\Supports\Carbon parse_from_locale(string $time, ?string $locale = null, \DateTimeZone|string|int|null $timezone = null)
 * @method static string plural_unit(string $unit)
 * @method static \Ecommerce\Supports\Carbon|null raw_create_from_format(string $format, string $time, $timezone = null)
 * @method static \Ecommerce\Supports\Carbon raw_parse(\DateTimeInterface|\Carbon\WeekDay|\Carbon\Month|string|int|float|null $time, \DateTimeZone|string|int|null $timezone = null)
 * @method static void reset_months_overflow()
 * @method static void reset_to_string_format()
 * @method static void reset_years_overflow()
 * @method static void serialize_using($callback)
 * @method static void set_fallback_locale(string $locale)
 * @method static void set_human_diff_options($human_diff_options)
 * @method static void set_locale(string $locale)
 * @method static void set_mid_day_at($hour)
 * @method static void set_test_now(mixed $test_now = null)
 * @method static void set_test_now_and_timezone(mixed $test_now = null, $timezone = null)
 * @method static void set_to_string_format(string|\Closure|null $format)
 * @method static void set_translator($translator)
 * @method static void set_week_ends_at($day)
 * @method static void set_week_starts_at($day)
 * @method static void set_weekend_days($days)
 * @method static bool should_overflow_months()
 * @method static bool should_overflow_years()
 * @method static string singular_unit(string $unit)
 * @method static void sleep(int|float $seconds)
 * @method static \Ecommerce\Supports\Carbon today(\DateTimeZone|string|int|null $timezone = null)
 * @method static \Ecommerce\Supports\Carbon tomorrow(\DateTimeZone|string|int|null $timezone = null)
 * @method static string translate_time_string(string $time_string, ?string $from = null, ?string $to = null, int $mode = \Carbon\CarbonInterface::TRANSLATE_ALL)
 * @method static string translate_with($translator, string $key, array $parameters = [], $number = null)
 * @method static void use_months_overflow($months_overflow = true)
 * @method static void use_strict_mode($strict_mode_enabled = true)
 * @method static void use_years_overflow($years_overflow = true)
 * @method static mixed with_test_now(mixed $test_now, callable $callback)
 * @method static with_time_zone(\DateTimeZone|string|int|null $timezone)
 * @method static \Ecommerce\Supports\Carbon yesterday(\DateTimeZone|string|int|null $timezone = null)
 * @method static bool is_valid_date($value)
 * @method static string to_sql_datetime_string()
 * 
 * @see \Ecommerce\Core\Managers\DateManager
 */
class Date extends Facade
{
    public static function get_accessor()
    {
        return 'date';
    }
}
