export { default as CustomerProfileCard } from './components/customer-profile-card';
export { default as CustomerSelectionField } from './components/fields/customer-selection-field';
export { default as BillingAddress } from './pages/customer-details/billing-address';
export { default as CustomerOverview } from './pages/customer-details/customer-overview';
export { default as ShippingAddress } from './pages/customer-details/shipping-address';
export type { Customer, CustomerAddress, CustomerInfo } from './schemas/catalog/customer';
export { CustomerAddressSchema, CustomerInfoSchema } from './schemas/catalog/customer';
export type { CustomerFormInput, CustomerFormPayload } from './schemas/forms/customer-form';
export { CustomerFormSchema } from './schemas/forms/customer-form';
export { useCreateCustomerMutation, useCustomerQuery, useCustomersQuery } from './services/customer';
export { customerKeys } from './services/query-keys';
export { customerListOptions } from './types';
